from .engulfing_flames_debuff import EngulfingFlamesDebuff
from .fire_ball_debuff import FireBallDebuff
from .fire_frogs_debuff import FireFrogsDebuff
from .searing_blaze_debuff import SearingBlazeDebuff
from .incinerate_debuff import IncinerateDebuff
